modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dimadencep/Blur-Forge/issues"
license = "MIT"

[[mods]]
modId = "blur"
version = "${version}"
displayURL = "https://modrinth.com/mod/blur-forge"
displayName = "Blur (Forge)"
authors = "dima_dencep, tterrag1098, Motschen, Pyrofab, backryun, byquanton"
description = "Modifies the background behind Minecraft GUIs to have a blur effect"
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.blur]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.blur]]
modId = "satin"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.blur]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"