modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/blur-forge/issues"
license = "MIT"

[[mods]]
modId = "blur"
version = "${version}"
displayURL = "https://curseforge.com/minecraft/mc-mods/blur-forge"
displayName = "Blur (Forge)"
updateJSONURL = "https://api.modrinth.com/updates/rubidium-extra/forge_updates.json"
authors = "dima_dencep, tterrag1098, Motschen, Pyrofab, backryun, byquanton"
description = "Modifies the background behind Minecraft GUIs to have a blur effect"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.blur]]
modId = "satin"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
